debug: true
server:
  port: 8081
#  servlet:
#    context-path: /mall
# 数据库连接
spring:
  redis:
    host: 127.0.0.1
    port: 6379
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dnc?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: rootroot
# mybatis
mybatis:
  typeAliasesPackage: com.customer.entity
  mapperLocations:  classpath:mapper/**.xml
# 日志配置
logging:
  config: classpath:config/logback-spring.xml