spring:
  # 应用程序名称
  application:
    name: mall
  thymeleaf:
    cache: false
  # 当前环境名称（注意：不可设置为 test 它是单元测试专用的名称）
  profiles:
    active: dev
#    active: pro
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure:
            logging: info